---
- name: Install nginx package
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart-nginx

- name: Remove nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx logrotate conf
  copy:
    src: nginx.logrotate
    dest: /etc/logrotate.d/nginx

- name: Set permission to access log
  file:
    path: /var/log/nginx/access.log
    mode: 0644

- name: Create nginx systemd service file
  copy:
    src: nginx.service
    dest: /lib/systemd/system/nginx.service
  notify: restart-nginx
