---
chain: polkadot

node_binary_url: https://github.com/paritytech/polkadot/releases/download/v0.8.30/polkadot
node_binary_name: polkadot
node_chain_name: polkadot
node_db_disk_label: CHAIN_DB

node_relaychain_extra_args:
- '--validator'
- '--pruning=archive'
- '--prometheus-external'
- '--prometheus-port 9615'
- '--in-peers=30'
- '--out-peers=30'

node_user: polkadot
node_group: polkadot
node_log_dir: /var/log/polkadot

node_rpc_url: RPC_URL
node_safe_restart: true

static_reserved_nodes:
- /ip4/1.2.3.4/tcp/30333/p2p/12D3Kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- /ip4/2.3.4.5/tcp/30333/p2p/12D3Kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- /ip4/3.3.4.5/tcp/30333/p2p/12D3Kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
