---
node_relaychain_extra_args:
- '--validator'
- '--pruning=archive'
- '--prometheus-external'
- '--prometheus-port 9615'
- '--in-peers=30'
- '--out-peers=30'
- "--unsafe-ws-external"
- "--unsafe-rpc-external"
- "--rpc-cors all"
