rococo_parachain_collator:
  vars:
    ansible_user: SSH_USER
  hosts:
    scaleway-rococo-parachain-collator1:
      ansible_host: xxx
      internal_addr: xxx
      node_parachain_args:
      - '--collator'
      - '--parachain-id 200'
      - '--port 40334' 
      - '--rpc-port 9934'
      - '--ws-port 9944'
      - '--rpc-cors all'
      - '--alice'
      node_relaychain_extra_args:
      - '--port 30333'
      - '--execution wasm' 
      - '--rpc-port 9933' 
      - '--ws-port 9977'
    scaleway-rococo-parachain-collator2:
      ansible_host: xxx
      internal_addr: xxx
      node_parachain_args:
      - '--collator'
      - '--parachain-id 300'
      - '--port 40334'
      - '--rpc-port 9934'
      - '--ws-port 9944'
      - '--unsafe-ws-external'
      - '--unsafe-rpc-external'
      - '--rpc-cors all'
      - '--alice'
      node_relaychain_extra_args:
      - '--port 30333'
      - '--execution wasm'
      - '--rpc-port 9933'
      - '--ws-port 9977'
