polkadot_node:
  vars:
    ansible_user: SSH_USER
  hosts:
    validator1:
      ansible_host: xxx
      internal_addr: xxx
      role: validator
      basket: basket1
    validator2:
      ansible_host: xxx
      internal_addr: xxx
      role: validator
      basket: basket2

