---
mtail_user: mtail
mtail_group: mtail
mtail_home_dir: /opt/mtail
mtail_binary_dir: /usr/local/bin
mtail_url: https://github.com/google/mtail/releases/download/v3.0.0-rc41/mtail_3.0.0-rc41_Linux_x86_64.tar.gz
