---
- name: Get peerid
  uri:
    url: "http://localhost:{{ node_rpc_port }}/"
    method: POST
    body_format: json
    return_content: yes
    body: {"id":1, "jsonrpc":"2.0", "method": "system_localPeerId"}
  register: peerid
  delegate_to: "{{ item }}"
  become: no
  until: peerid.status == 200
  retries: 3
  delay: 5

- name: Set reserved nodes
  uri:
    url: "http://localhost:{{ node_rpc_port }}/"
    method: POST
    body_format: json
    return_content: yes
    body: {"id":1, "jsonrpc":"2.0", "method": "system_addReservedPeer","params": ["/ip4/{{ item }}/tcp/{{ node_listen_port }}/p2p/{{ peerid.json['result'] }}"]}
  register: result
  until: result.status == 200
  retries: 3
  delay: 5

- name: Result
  debug:
    msg: "/ip4/{{ item }}/tcp/{{ node_listen_port }}/p2p/{{ peerid.json['result'] }}"
